apiVersion: v1
kind: Namespace
metadata:
  name: cnb-springboot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: cnb-springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      role: app
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
      labels:
        role: app
    spec:
      containers:
        - env:
            - name: APP_TITLE
              value: DEV
          image: harbor.run.haas-243.pez.pivotal.io/dev/cnb-springboot
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 2
          name: app
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
          resources:
            limits:
              memory: 1Gi
