management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
server:
  port: ${PORT:8080}

app:
  message: Hello Neven!
  title: Spring Boot with Cloud-native Buildpacks
